
name = "DashSplit"
uuid = "1b08a953-4be3-4667-9a23-f9339da137a6"
authors = ["Tom Catshoek <tomcatshoek@zeelandnet.nl>"]
version = "0.0.3"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
